#!/bin/sh

print_usage()
{
    echo "usage: $0 {start|stop}"
}

case "$1" in
    start)
        mvn clean package -Dmaven.test.skip=true
#        nohup java -jar target/ow-server.jar --spring.config.location=conf/application.properties &
        ;;
    stop)
        ps aux|grep ow-server | grep -v grep | awk '{print $2}' | xargs kill -9
        ;;
    restart)
        ps aux|grep ow-server | grep -v grep | awk '{print $2}' | xargs kill -9
        mvn clean package -Dmaven.test.skip=true
 #       nohup java -jar target/ow-server.jar --spring.config.location=conf/application.properties &
        ;;
    *)
        print_usage
esac
